import test from 'node:test';import assert from 'node:assert/strict';import {NullEngine,Scene,VertexBuffer} from '@babylonjs/core';import {createHero3D,HERO_PROFILES} from '../dist/hero-3d.js';
test('blink and ambient gestures change only presentation and reset under reduced motion',()=>{
 const engine=new NullEngine(),scene=new Scene(engine),rig=createHero3D(scene,'gestures','villager'),position={x:3,y:2,z:1};
 try{let blinked=false;for(let t=0;t<=5000;t+=50){rig.update(position,t);if(scene.getMeshByName('gestures:eye-1').scaling.y<.02)blinked=true;}assert.equal(blinked,true);for(const [i,gesture] of ['wave','chop','sneeze','play'].entries()){rig.update(position,5100+i*100,false,0,gesture);assert.deepEqual(rig.root.position.asArray(),[3,2,1]);}rig.update(position,5600,true,0,'sneeze');assert.equal(scene.getTransformNodeByName('gestures:head').rotation.x,0);assert.equal(Math.abs(scene.getTransformNodeByName('gestures:arm1').rotation.x),0);assert.equal(scene.getMeshByName('gestures:eye-1').scaling.y,.07);}finally{rig.dispose();scene.dispose();engine.dispose();}
});
test('entire roster has distinct profiles, real geometry and disposable rigs',()=>{const engine=new NullEngine(),scene=new Scene(engine);try{assert.equal(Object.keys(HERO_PROFILES).length,6);assert.equal(new Set(Object.values(HERO_PROFILES).map(p=>JSON.stringify(p))).size,6);for(const skin of Object.keys(HERO_PROFILES)){const rig=createHero3D(scene,skin,skin);assert.ok(rig.root.getChildMeshes().length>20);rig.update({x:10,y:2,z:3},0);assert.deepEqual(rig.root.position.asArray(),[10,2,3]);rig.dispose();assert.equal(rig.disposed,true);assert.throws(()=>rig.update({x:0,y:0,z:0},1));}assert.equal(scene.meshes.length,0);}finally{scene.dispose();engine.dispose();}});
test('cape pins stay anchored, wind deforms the hem and all geometry remains finite',()=>{const engine=new NullEngine(),scene=new Scene(engine),rig=createHero3D(scene,'s','seraphine');try{const before=Array.from(rig.cape.getVerticesData(VertexBuffer.PositionKind));rig.update({x:0,y:0,z:0},0);rig.update({x:0,y:0,z:0},100, false,12);const after=Array.from(rig.cape.getVerticesData(VertexBuffer.PositionKind));assert.deepEqual(after.slice(0,21),before.slice(0,21));assert.notDeepEqual(after.slice(21),before.slice(21));assert.ok(after.every(Number.isFinite));assert.deepEqual(rig.root.position.asArray(),[0,0,0]);assert.throws(()=>rig.update({x:0,y:0,z:0},200,false,Infinity));}finally{rig.dispose();scene.dispose();engine.dispose();}});
test('walking follows server positions, pause stabilizes secondary motion, equipment swaps do not leak meshes',()=>{const engine=new NullEngine(),scene=new Scene(engine),rig=createHero3D(scene,'a','adventurer');try{rig.update({x:0,y:0,z:0},0);rig.update({x:1,y:2,z:0},100);assert.deepEqual(rig.root.position.asArray(),[1,2,0]);rig.update({x:1,y:2,z:0},200,true);const a=Array.from(rig.cape.getVerticesData(VertexBuffer.PositionKind));rig.update({x:1,y:2,z:0},300,true);assert.deepEqual(Array.from(rig.cape.getVerticesData(VertexBuffer.PositionKind)),a);const base=scene.meshes.length;for(let n=0;n<10;n++){rig.weapon('reed_blade');assert.equal(scene.meshes.length,base+1);rig.weapon('ash_staff');assert.equal(scene.meshes.length,base+1);rig.weapon(null);assert.equal(scene.meshes.length,base);}}finally{rig.dispose();scene.dispose();engine.dispose();}});
test('active drill gestures articulate the rig and reset cleanly when paused',()=>{const engine=new NullEngine(),scene=new Scene(engine),rig=createHero3D(scene,'drill','seraphine'),p={x:0,y:0,z:0};try{const arm=scene.getTransformNodeByName('drill:arm1');for(const [i,gesture] of ['brace','aim','focus','balance'].entries()){const t=i*1200;rig.update(p,t,true);const idle=arm.rotation.asArray();rig.update(p,t+1000,false,0,gesture);assert.notDeepEqual(arm.rotation.asArray(),idle);assert.ok(rig.root.getChildTransformNodes().every(n=>n.rotation.asArray().every(Number.isFinite)));rig.update(p,t+1100,true,0,gesture);assert.deepEqual(arm.rotation.asArray(),idle);}assert.deepEqual(rig.root.position.asArray(),[0,0,0]);}finally{rig.dispose();scene.dispose();engine.dispose();}});
