import test from 'node:test';import assert from 'node:assert/strict';import {NullEngine,Scene,VertexBuffer} from '@babylonjs/core';import {createHero3D,HERO_PROFILES} from '../dist/hero-3d.js';import {appearanceForSkin,checkedAppearance,SKIN_TONES} from '../dist/hero-appearance.js';
test('all roster models contain detailed faces, clothed anatomy and a bounded joint/mesh budget',()=>{
 const engine=new NullEngine(),scene=new Scene(engine);
 try{for(const skin of Object.keys(HERO_PROFILES)){const h=createHero3D(scene,'anatomy-'+skin,skin);for(const prefix of ['face','nose-bridge','nose','nostril','chin','jawline','cheekbone','ear-fold','eyebrow','lash','pupil','eye-glint','neck','clavicle','underarm-seam','ribcage','abdomen','spine-seam','seat','quadriceps','kneecap','calf','heel','toe-cap','biceps','forearm','wrist','finger','thumb'])assert.ok(h.details.some(v=>v.startsWith(prefix)),skin+':'+prefix);assert.equal(Object.keys(h.joints).length,16);assert.ok(h.root.getChildMeshes().length<=60);assert.ok(h.details.length>100);for(const mesh of h.root.getChildMeshes()){assert.equal(mesh.isPickable,false);assert.equal(mesh.checkCollisions,false);for(const kind of [VertexBuffer.PositionKind,VertexBuffer.NormalKind,VertexBuffer.ColorKind]){const data=mesh.getVerticesData(kind);if(data)assert.ok([...data].every(Number.isFinite));}}h.dispose();assert.equal(scene.meshes.length,0);assert.equal(scene.materials.length,0);}}finally{scene.dispose();engine.dispose();}
});
test('appearance validation is strict, detached and palette-bounded before allocating a rig',()=>{
 const preset=appearanceForSkin('seraphine');assert.equal(Object.isFrozen(preset),true);const edited={...preset,skinTone:5,facialHair:'beard',hairStyle:'cropped',build:'strong'};const saved=checkedAppearance(edited);edited.skinTone=0;assert.equal(saved.skinTone,5);
 const engine=new NullEngine(),scene=new Scene(engine);try{for(const change of [{skinTone:-1},{skinTone:6},{hairColor:1.2},{eyeColor:NaN},{makeup:'unknown'},{build:'huge'},{extra:1}]){assert.throws(()=>createHero3D(scene,'invalid','seraphine',{...preset,...change}));assert.equal(scene.meshes.length,0);assert.equal(scene.transformNodes.length,0);}for(let tone=0;tone<SKIN_TONES.length;tone++){const h=createHero3D(scene,'tone'+tone,'seraphine',{...preset,skinTone:tone});assert.equal(h.profile.skin,SKIN_TONES[tone]);assert.ok(h.root.getChildMeshes().some(m=>m.getVerticesData(VertexBuffer.ColorKind)?.length>0));h.dispose();}}finally{scene.dispose();engine.dispose();}
});
test('knees and elbows articulate in motion, wrists and speaking gestures reset fully on pause',()=>{
 const engine=new NullEngine(),scene=new Scene(engine),h=createHero3D(scene,'joints','adventurer'),origin={x:0,y:0,z:0};
 try{h.update(origin,0);let bent=false;for(let i=1;i<=20;i++){h.update({x:0,y:0,z:i*.1},i*50);bent||=Object.values(h.joints).some(n=>n.name.includes(':knee')&&Math.abs(n.rotation.x)>.05);}assert.equal(bent,true);assert.ok(h.joints.knee1.rotation.x>=0&&h.joints['knee-1'].rotation.x>=0);assert.ok(h.joints.elbow1.rotation.x<0);h.update({x:0,y:0,z:2},1100,false,0,'wave');assert.ok(h.joints.elbow1.rotation.x<-.5);assert.equal(scene.getMeshByName('joints:teeth').isEnabled(),true);h.update({x:0,y:0,z:2},1150,true);for(const name of ['knee-1','knee1','ankle-1','ankle1','elbow-1','elbow1','wrist1','wrist-1','jaw','pelvis'])assert.deepEqual(h.joints[name].rotation.asArray(),[0,0,0]);assert.equal(scene.getMeshByName('joints:teeth').isEnabled(),false);assert.deepEqual(origin,{x:0,y:0,z:0});assert.deepEqual(h.root.position.asArray(),[0,0,2]);}finally{h.dispose();scene.dispose();engine.dispose();}
});
test('static batches retain anatomy labels and stable material/mesh counts through equipment and motion',()=>{
 const engine=new NullEngine(),scene=new Scene(engine),h=createHero3D(scene,'batch','seraphine');try{const batch=h.root.getChildMeshes().find(m=>m.metadata?.features?.includes('face'));assert.ok(batch);assert.ok(batch.metadata.features.includes('nose'));const baseline=scene.meshes.length;for(let i=0;i<200;i++){h.update({x:0,y:0,z:i*.02},i*20,false,3);assert.equal(scene.meshes.length,baseline);}for(const weapon of ['reed_blade','ash_staff','granite_maul']){h.weapon(weapon);assert.equal(scene.meshes.length,baseline+1);assert.equal(scene.getMeshByName('batch:weapon').parent,h.joints.wrist1);}h.weapon(null);assert.equal(scene.meshes.length,baseline);h.dispose();assert.equal(scene.meshes.length,0);assert.equal(scene.materials.length,0);}finally{h.dispose();scene.dispose();engine.dispose();}
});
