import test from 'node:test';import assert from 'node:assert/strict';import {NullEngine,Scene} from '@babylonjs/core';
import {GameActions,decodeAction,decodeGameState,checkedPersistentPlayerState,freshPersistentPlayerState} from '../dist/game-actions.js';import {ALL_SKILLS} from '../dist/skill-directory.js';import {PRACTICE_METHODS} from '../dist/practice.js';import {PRACTICE_VERBS,practiceResponse} from '../dist/practice-interaction.js';import {createPracticeYard,PRACTICE_FIXTURES} from '../dist/practice-yard-3d.js';import {createRealmScene} from '../dist/realm-scene.js';
const camp={x:0,y:0,z:0},beacon={x:30,y:0,z:0},far={x:24,y:0,z:0};const packet=(sequence,value,action='practice')=>JSON.stringify({kind:'action',sequence,action,value});
const setup=()=>{const g=new GameActions(beacon,camp);g.join('a','p1');return g;};const xp=s=>({...s.progression.xp,...s.skilling.xp});const send=(g,value,action='practice',pos=camp)=>{const seq=g.inspection().players.find(p=>p.id==='p1').sequence+1;assert.ok(g.receive('a',packet(seq,value,action)));g.commit(()=>pos);return g.snapshot('a',[]);};
function settle(g,c,pos=camp){while(g.snapshot('a',[]).tick<c.readyTick-1)g.commit(()=>pos);}
function finish(g,pos=camp){for(let i=0;i<3;i++){const c=g.snapshot('a',[]).practiceChallenge;assert.ok(c);settle(g,c,pos);const s=send(g,practiceResponse(c,c.target),'practice-step',pos);assert.equal(s.result.code,i===2?(c.reward==='gathering'?'skill_gathered':'practice_done'):'practice_step');}return g.persistentState('a');}
test('all23 skills use themed three-step drills; start and partial actions award no XP',()=>{for(const skill of ALL_SKILLS){const g=setup(),before=g.persistentState('a');assert.equal(send(g,skill).result.code,'practice_started');assert.deepEqual(xp(g.persistentState('a')),xp(before));assert.equal(PRACTICE_VERBS[skill].length,3);const after=finish(g);for(const k of ALL_SKILLS)assert.equal(xp(after)[k]-xp(before)[k],k===skill?1:0);assert.deepEqual(after.inventory,before.inventory);assert.deepEqual(after.skilling.pack,before.skilling.pack);assert.deepEqual(after.skilling.bank,before.skilling.bank);assert.equal(after.progression.mode,before.progression.mode);}assert.deepEqual(Object.keys(PRACTICE_METHODS).sort(),[...ALL_SKILLS].sort());});
test('fixed-coordinate autoclicking and queued rapid steps cannot finish a drill',()=>{const g=setup();send(g,'mining');let c=g.snapshot('a',[]).practiceChallenge;settle(g,c);send(g,practiceResponse(c,c.target),'practice-step');const next=g.snapshot('a',[]).practiceChallenge;assert.notEqual(next.target,c.target);settle(g,next);send(g,practiceResponse(next,c.target),'practice-step');assert.equal(g.snapshot('a',[]).result.code,'practice_miss');assert.equal(g.persistentState('a').skilling.xp.mining,0);assert.equal(g.snapshot('a',[]).practiceChallenge,null);const h=setup();send(h,'attack');c=h.snapshot('a',[]).practiceChallenge;for(let i=1;i<=8;i++)assert.ok(h.receive('a',packet(i,practiceResponse(c,c.target),'practice-step')));assert.equal(h.receive('a',packet(9,'attack')),false);h.commit(()=>camp);assert.equal(h.snapshot('a',[]).practiceChallenge.step,0);assert.equal(h.snapshot('a',[]).result.code,'practice_early');assert.equal(h.persistentState('a').progression.xp.attack,0);});
test('stale tokens, old steps, duplicate packets and another player cannot reuse a response',()=>{const g=setup();g.join('b','p2');send(g,'attack');const c=g.snapshot('a',[]).practiceChallenge;settle(g,c);send(g,practiceResponse(c,c.target),'practice-step');assert.equal(send(g,practiceResponse(c,c.target),'practice-step').result.code,'practice_stale');assert.equal(send(g,'p9-999-999/1/0','practice-step').result.code,'practice_stale');assert.equal(g.receive('a',packet(0,'mining')),false);g.receive('b',packet(0,practiceResponse(c,c.target),'practice-step'));g.commit(()=>camp);assert.equal(g.snapshot('b',[]).result.code,'practice_stale');assert.equal(g.snapshot('a',[]).practiceChallenge.step,1);});
test('shared attempt recovery survives skill cycling, cancellation, disconnect and fresh clock',()=>{const g=setup();send(g,'agility');assert.equal(send(g,'mining').result.code,'practice_busy');send(g,'cancel','practice-step');assert.equal(send(g,'mining').result.code,'practice_wait');const saved=g.persistentState('a');assert.ok(saved.practiceReadyTick>0);assert.equal(saved.skilling.xp.agility,0);g.leave('a');const h=setup();h.leave('a');h.join('a','p1',saved);assert.equal(h.snapshot('a',[]).practiceChallenge,null);assert.equal(send(h,'mining').result.code,'practice_wait');while(h.snapshot('a',[]).tick<saved.practiceReadyTick-1)h.commit(()=>camp);assert.equal(send(h,'mining').result.code,'practice_started');finish(h);assert.equal(h.persistentState('a').skilling.xp.mining,1);});
test('expiry and leaving the yard invalidate incomplete drills without XP',()=>{for(const action of ['expiry','range']){const g=setup();send(g,'mining');const c=g.snapshot('a',[]).practiceChallenge;if(action==='expiry'){while(g.snapshot('a',[]).tick<c.expiresTick)g.commit(()=>camp);}else g.commit(()=>far);assert.equal(g.snapshot('a',[]).practiceChallenge,null);assert.equal(send(g,practiceResponse(c,c.target),'practice-step').result.code,'practice_stale');assert.equal(g.persistentState('a').skilling.xp.mining,0);}});
test('last-moment partial response ends gracefully rather than faulting the host',()=>{const g=setup();send(g,'mining');const c=g.snapshot('a',[]).practiceChallenge;while(g.snapshot('a',[]).tick<c.expiresTick-2)g.commit(()=>camp);assert.equal(send(g,practiceResponse(c,c.target),'practice-step').result.code,'practice_miss');assert.equal(g.snapshot('a',[]).practiceChallenge,null);});
test('all existing gathering paths require three actions before any resource or25XP reward',()=>{for(const skill of ['woodcutting','mining','fishing']){const g=setup();assert.equal(send(g,skill,'skilling',far).result.code,'practice_started');assert.equal(g.persistentState('a').skilling.xp[skill],0);assert.equal(Object.values(g.persistentState('a').skilling.pack).reduce((a,b)=>a+b,0),0);const saved=finish(g,far);assert.equal(saved.skilling.xp[skill],25);assert.equal(Object.values(saved.skilling.pack).reduce((a,b)=>a+b,0),1);assert.equal(send(g,skill,'skilling',far).result.code,'skill_wait');}});
test('unknown skills, client grants, identities, clocks, fabricated responses and extra fields fail closed',()=>{for(const value of ['all','constructor','__proto__',null,{},42])assert.throws(()=>decodeAction(packet(0,value)));for(const extra of [{xp:1e6},{id:'p2'},{tick:1e6},{position:camp}])assert.throws(()=>decodeAction(JSON.stringify({...JSON.parse(packet(0,'mining')),...extra})));for(const value of ['0-0/3/0','0-0/0/4','0-0/0/NaN','abc',null])assert.throws(()=>decodeAction(packet(0,value,'practice-step')));for(const tick of [-1,101,1.5,Infinity])assert.throws(()=>checkedPersistentPlayerState({...freshPersistentPlayerState(),practiceReadyTick:tick}));});
test('private challenges are detached, strictly validated and absent for other observers',()=>{const g=setup();g.join('b','p2');send(g,'magic');const state=g.snapshot('a',[]);assert.equal(g.snapshot('b',['p1']).practiceChallenge,null);assert.equal(g.snapshot('',[]).practiceChallenge,null);const c=structuredClone(state.practiceChallenge);state.practiceChallenge.target=(c.target+1)%4;assert.equal(g.snapshot('a',[]).practiceChallenge.target,c.target);for(const patch of [{target:4},{step:3},{readyTick:state.tick+21},{expiresTick:state.tick},{reward:'gold'},{skill:'unknown'},{extra:1}])assert.throws(()=>decodeGameState(JSON.stringify({...state,practiceChallenge:{...c,...patch}})));assert.throws(()=>decodeGameState(JSON.stringify({...g.snapshot('',[]),practiceChallenge:c})));});
test('XP cap cannot wrap; v4 saves migrate without restoring an active drill',()=>{const save=freshPersistentPlayerState();save.progression.xp.magic=200000000;const g=setup();g.leave('a');g.join('a','p1',save);assert.equal(send(g,'magic').result.code,'practice_full');assert.equal(g.snapshot('a',[]).practiceChallenge,null);const {practiceReadyTick,...old}=freshPersistentPlayerState();old.version=4;old.skilling.xp.agility=83;const migrated=checkedPersistentPlayerState(old);assert.equal(migrated.version,5);assert.equal(migrated.practiceReadyTick,0);assert.equal(migrated.skilling.xp.agility,83);});
test('dead players gain no XP; failed staged transition cannot partly start a drill',()=>{const g=setup();g.players.get('a').fighter.hp=0;assert.equal(send(g,'prayer').result.code,'recovering');assert.equal(g.persistentState('a').progression.xp.prayer,0);const h=setup();h.join('b','p2');for(const c of ['a','b'])h.receive(c,packet(0,'mining'));const before=h.inspection();assert.throws(()=>h.stagedCommit(c=>{if(c==='b')throw Error('position lookup failed');return camp;}));assert.deepEqual(h.inspection(),before);});
test('yard fixtures remain checked, small, nonpickable and disposable',()=>{const realm=createRealmScene();for(const f of PRACTICE_FIXTURES)assert.ok(realm.navigation.check({x:realm.plan.start.x+f.dx,y:realm.plan.start.y,z:realm.plan.start.z+f.dz}).ok);const engine=new NullEngine(),scene=new Scene(engine),yard=createPracticeYard(scene,realm.plan.start,p=>realm.navigation.check(p));assert.ok(yard.meshes.every(m=>!m.isPickable));yard.dispose();assert.equal(scene.meshes.length,0);scene.dispose();engine.dispose();});
