import test from 'node:test';import assert from 'node:assert/strict';import WebSocket from 'ws';
import {RealmRuntime} from '../dist/realm-runtime.js';import {NavigationWorld} from '../dist/navigation.js';import {REALM_SUBPROTOCOL,encodeHello} from '../dist/realm-contract.js';
import {ReplayJournal,replayJournal,parseJournal,stateHash,canonical} from '../tools/replay-journal.mjs';import {createLocalRealmServer} from '../tools/realm-server.mjs';
const nav=()=>new NavigationWorld(()=>({height:0,slopeDegrees:0,waterDepth:0}),{bounds:{minX:-20,maxX:20,minZ:-20,maxZ:20}}),options={capacity:8,visibilityRadius:64,beacon:{x:0,y:0,z:0}};
function record(budget){const r=new RealmRuntime(nav(),options),j=new ReplayJournal(r,options,budget);r.join('secret-connection-uuid',{x:0,z:0});j.join('secret-connection-uuid',{x:0,z:0},r);for(let i=0;i<12;i++){const text=JSON.stringify({sequence:i,dx:i%2?1:0,dz:0});r.receive('secret-connection-uuid',text);j.input('secret-connection-uuid',text,r);r.advance(50);j.advance(50,r);}return {r,j};}
test('100 recorded replays reproduce every event and final SHA-256',()=>{const {r,j}=record(),text=JSON.stringify(j.export());assert.equal(text.includes('secret-connection-uuid'),false);for(let i=0;i<100;i++)assert.equal(replayJournal(text,nav()).hash,stateHash(r));});
test('replay rejects tampering, wrong contracts and unknown opcodes',()=>{const good=record().j.export();for(const mutate of [j=>j.events[1].packet=JSON.stringify({sequence:0,dx:1,dz:0}),j=>j.contract.simulationRevision=99,j=>j.events[1].op='execute',j=>j.extra=true,j=>j.finalHash='0'.repeat(64)]){const j=structuredClone(good);mutate(j);assert.throws(()=>replayJournal(JSON.stringify(j),nav()));}});
test('bounded recorder marks a valid prefix incomplete and does not stop gameplay',()=>{const {r,j}=record({maxEvents:4});assert.equal(r.tick,12);assert.equal(j.export().complete,false);assert.equal(j.export().events.length,4);assert.throws(()=>replayJournal(JSON.stringify(j.export()),nav()),/incomplete/);assert.equal(replayJournal(JSON.stringify(j.export()),nav(),{allowPrefix:true}).events,4);});
test('canonical state orders keys and rejects invalid numbers',()=>{assert.equal(canonical({b:2,a:{d:1,c:0}}),canonical({a:{c:0,d:1},b:2}));for(const x of [NaN,Infinity,undefined])assert.throws(()=>canonical(x));});
test('journal output cannot mutate recorder and malformed clock is rejected',()=>{const j=record().j,copy=j.export();copy.events.length=0;assert.ok(j.export().events.length>0);const bad=j.export();bad.events.find(e=>e.op==='advance').elapsedMs=1e10;assert.throws(()=>parseJournal(JSON.stringify(bad)));});
async function until(fn){for(let i=0;i<500;i++){if(fn())return;await new Promise(r=>setTimeout(r,5));}throw new Error('timeout');}
test('real socket recording includes shared actions and replays on the same scene',async()=>{const host=await createLocalRealmServer({autoTick:false,recordReplay:true}),messages=[];const ws=new WebSocket(host.origin.replace('http:','ws:')+'/socket',REALM_SUBPROTOCOL,{origin:host.origin});try{ws.on('open',()=>ws.send(encodeHello()));ws.on('message',d=>messages.push(JSON.parse(d.toString())));await until(()=>messages.some(m=>m.kind==='welcome'));ws.send(JSON.stringify({kind:'action',sequence:0,action:'appearance',value:'elder'}));await until(()=>host.metrics.accepted===1);host.advance(100);await until(()=>messages.some(m=>m.kind==='game'&&m.players[0]?.skin==='elder'));const replay=replayJournal(JSON.stringify(host.exportReplay()),host.scene.navigation);assert.equal(replay.hash,stateHash(host.realm));}finally{ws.close();await host.close();}});
