import test from 'node:test';import assert from 'node:assert/strict';
import {GameActions,freshPersistentPlayerState,checkedPersistentPlayerState,decodeGameState,decodeAction} from '../dist/game-actions.js';
import {practiceResponse} from '../dist/practice-interaction.js';
import {freshSkilling,checkedSkilling,skillAction} from '../dist/skilling.js';
const camp={x:0,y:0,z:0},target={x:20,y:0,z:0},safe={x:14,y:0,z:0};
function setup(){const game=new GameActions(target,camp);game.join('a','p1');let sequence=0;return {game,act(value,pos=safe){assert.ok(game.receive('a',JSON.stringify({kind:'action',sequence:sequence++,action:'skilling',value})));game.commit(()=>pos);while(game.snapshot('a',[]).practiceChallenge){const c=game.snapshot('a',[]).practiceChallenge;while(game.snapshot('a',[]).tick<c.readyTick-1)game.commit(()=>pos);assert.ok(game.receive('a',JSON.stringify({kind:'action',sequence:sequence++,action:'practice-step',value:practiceResponse(c,c.target)})));game.commit(()=>pos);}return game.snapshot('a',[]);},wait(){for(let i=0;i<100;i++)game.commit(()=>safe);}};}
function gatherTrip(s){for(const value of ['woodcutting','mining','fishing'])for(let i=0;i<4;i++){s.act(value);s.wait();}}
test('three professions have exclusive XP, bounded pack, repeatable bank trips and no combat XP',()=>{const s=setup();gatherTrip(s);let state=s.game.snapshot('a',[]);assert.deepEqual(state.skilling.xp,{...freshSkilling().xp,woodcutting:100,mining:100,fishing:100});assert.deepEqual(state.skilling.pack,{logs:4,ore:4,fish:4,warden_essence:0});assert.equal(s.act('mining').result.code,'skill_pack_full');assert.equal(s.act('deposit',camp).result.code,'skill_banked');state=s.game.snapshot('a',[]);assert.equal(state.skilling.bank.ore,4);assert.equal(Object.values(state.skilling.pack).reduce((a,b)=>a+b),0);assert.ok(Object.entries(state.progression.xp).every(([k,v])=>v===(k==='hitpoints'?1154:0)));s.wait();assert.equal(s.act('mining').skilling.pack.ore,1);});
test('cooldowns, shared per-player skill clock, invalid commands and server range prevent client minting',()=>{const s=setup();assert.equal(s.act('woodcutting').result.code,'skill_gathered');assert.equal(s.act('mining').result.code,'skill_wait');assert.equal(s.act('fishing',camp).result.code,'skill_range');assert.equal(s.act('deposit',target).result.code,'skill_range');assert.equal(s.game.snapshot('a',[]).skilling.xp.mining,0);for(const value of ['bank_gold',999,{}])assert.throws(()=>decodeAction(JSON.stringify({kind:'action',sequence:0,action:'skilling',value})));assert.throws(()=>decodeAction(JSON.stringify({kind:'action',sequence:0,action:'skilling',value:'mining',amount:100})));});
test('artisan recipe consumes exact bank resources and essence once, yielding two resources',()=>{const s=freshSkilling();assert.equal(skillAction(s,'upgrade',0),'skill_requirements');s.xp={...freshSkilling().xp,woodcutting:100,mining:100,fishing:100};s.bank={logs:4,ore:4,fish:4,warden_essence:1};assert.equal(skillAction(s,'upgrade',1),'skill_upgraded');assert.deepEqual(s.bank,{logs:1,ore:1,fish:1,warden_essence:0});assert.equal(skillAction(s,'upgrade',2),'skill_requirements');assert.equal(skillAction(s,'mining',3),'skill_gathered');assert.equal(s.pack.ore,2);assert.equal(s.xp.mining,125);s.pack.logs=9;s.pack.ore=2;assert.equal(skillAction(s,'fishing',43),'skill_pack_full');assert.equal(s.pack.fish,0);});
test('a full integrated gather/bank/PvM/craft route awards one essence per contributing clear',()=>{const s=setup();gatherTrip(s);s.act('deposit',camp);assert.equal(s.act('upgrade',camp).result.code,'skill_requirements');s.game.join('b','p2');let sequence=100;
 for(let i=0;i<20;i++){assert.ok(s.game.receive('a',JSON.stringify({kind:'action',sequence:sequence++,action:'combat',value:'attack'})));s.game.commit(()=>target);for(let j=0;j<16;j++)s.game.commit(()=>safe);}
 let state=s.game.snapshot('a',[]);assert.equal(state.fighter.wins,1);assert.equal(state.skilling.bank.warden_essence,1);assert.equal(s.game.snapshot('b',[]).skilling.bank.warden_essence,0);for(let j=0;j<30;j++)s.game.commit(()=>safe);assert.equal(s.game.snapshot('a',[]).skilling.bank.warden_essence,1);
 assert.ok(s.game.receive('a',JSON.stringify({kind:'action',sequence:sequence++,action:'skilling',value:'upgrade'})));s.game.commit(()=>camp);state=s.game.snapshot('a',[]);assert.equal(state.skilling.toolTier,2);assert.equal(state.skilling.bank.warden_essence,0);assert.equal(state.skilling.bank.logs,1);});
test('strict saves migrate versions 1 and 2, preserve private banks and rebase gather cooldown on restore',()=>{const s=setup();s.act('mining');const save=s.game.persistentState('a');assert.equal(save.version,6);assert.equal(save.skilling.readyTick,40);s.game.leave('a');s.game.join('a','p2',save);assert.equal(s.act('fishing').result.code,'skill_wait');assert.equal(s.game.snapshot('a',[]).skilling.pack.ore,1);const {skilling,practiceReadyTick,resonance,...v2}=freshPersistentPlayerState();v2.version=2;delete v2.progression.xp.hitpoints;delete v2.progression.xp.prayer;assert.deepEqual(checkedPersistentPlayerState(v2).skilling,freshSkilling());const {progression,...v1}=v2;v1.version=1;assert.equal(checkedPersistentPlayerState(v1).version,6);assert.throws(()=>checkedPersistentPlayerState({...v2,skilling}));});
test('snapshot and save boundaries reject overflows, grants and private-state leakage',()=>{const s=setup();s.act('mining');s.game.join('b','p2');assert.equal(s.game.snapshot('b',['p1']).skilling.pack.ore,0);assert.deepEqual(Object.keys(s.game.snapshot('b',['p1']).players[0]).sort(),['id','skin','weapon']);const detached=s.game.snapshot('a',[]);detached.skilling.bank.ore=999;assert.equal(s.game.snapshot('a',[]).skilling.bank.ore,0);assert.throws(()=>decodeGameState(JSON.stringify({...s.game.snapshot('a',[]),skilling:null})));for(const patch of [{toolTier:4},{readyTick:-1},{extra:1},{xp:{woodcutting:0,mining:'1',fishing:0}},{bank:{logs:1000001,ore:0,fish:0,warden_essence:0}},{pack:{logs:12,ore:1,fish:0,warden_essence:0}}])assert.throws(()=>checkedSkilling({...freshSkilling(),...patch}));});
test('bank capacity rejection and failed staged commits preserve all resources and XP',()=>{const s=freshSkilling();s.bank.ore=1000000;s.pack.ore=1;const before=structuredClone(s);assert.equal(skillAction(s,'deposit',0),'skill_bank_full');assert.deepEqual(s,before);const g=new GameActions(target,camp);g.join('a','p1');g.join('b','p2');for(const c of ['a','b'])g.receive(c,JSON.stringify({kind:'action',sequence:0,action:'skilling',value:'mining'}));const original=g.inspection();assert.throws(()=>g.commit(c=>{if(c==='b')throw Error('fault');return safe;}));assert.deepEqual(g.inspection(),original);});
test('Masterwork requires the second milestone, spends once, persists and cannot bypass Artisan',()=>{const s=freshSkilling();s.xp={...freshSkilling().xp,woodcutting:1600,mining:1600,fishing:1600};s.bank={logs:23,ore:23,fish:23,warden_essence:6};assert.equal(skillAction(s,'upgrade',0),'skill_upgraded');assert.equal(s.toolTier,2);assert.equal(s.bank.logs,20);assert.equal(skillAction(s,'upgrade',1),'skill_upgraded');assert.equal(s.toolTier,3);assert.deepEqual(s.bank,{logs:0,ore:0,fish:0,warden_essence:0});assert.equal(skillAction(s,'upgrade',2),'skill_max_tool');assert.equal(skillAction(s,'woodcutting',3),'skill_gathered');assert.equal(s.pack.logs,3);const save=freshPersistentPlayerState();save.skilling={...s,readyTick:40};assert.equal(checkedPersistentPlayerState(save).skilling.toolTier,3);});
