import test from 'node:test';import assert from 'node:assert/strict';
import {RealmRuntime} from '../dist/realm-runtime.js';import {NavigationWorld} from '../dist/navigation.js';import {GameActions} from '../dist/game-actions.js';
const nav=()=>new NavigationWorld(()=>({height:0,slopeDegrees:0,waterDepth:0}),{bounds:{minX:-20,maxX:20,minZ:-20,maxZ:20}});
const move=JSON.stringify({sequence:0,dx:1,dz:0}),light=JSON.stringify({kind:'action',sequence:0,action:'beacon',value:'light'});
function setup(){const r=new RealmRuntime(nav(),{beacon:{x:0,y:0,z:0}});r.join('a',{x:0,z:0});r.join('b',{x:10,z:0});r.receive('a',move);r.receive('a',light);return r;}
test('movement, beacon and tick commit together at the first fixed tick',()=>{const r=setup();r.advance(49);assert.equal(r.tick,0);assert.equal(r.gameStateFor('a').beacon.lit,false);r.advance(1);assert.equal(r.tick,1);assert.equal(r.stateFor('a').position.x,.2);assert.equal(r.gameStateFor('a').result.code,'lit');});
test('game reducer failure discards already-calculated movement and game candidates',()=>{const r=setup(),before=r.inspection(),original=GameActions.prototype.stagedCommit;try{GameActions.prototype.stagedCommit=function(fn){original.call(this,fn);throw new Error('action fault');};assert.throws(()=>r.advance(50),/action fault/);assert.deepEqual(r.inspection(),before);assert.equal(r.status,'faulted');assert.throws(()=>r.gameStateFor('a'),/faulted/);}finally{GameActions.prototype.stagedCommit=original;}});
test('final combined invariant failure discards both reducers',()=>{const r=setup(),before=r.inspection(),original=GameActions.prototype.validate;try{GameActions.prototype.validate=()=>{throw new Error('invariant fault');};assert.throws(()=>r.advance(50),/invariant fault/);assert.deepEqual(r.inspection(),before);}finally{GameActions.prototype.validate=original;}});
test('catch-up actions resolve on first tick, not end-of-batch position',()=>{const r=new RealmRuntime(nav(),{beacon:{x:0,y:0,z:0}});r.join('a',{x:2.7,z:0});r.receive('a',move);r.receive('a',light);r.advance(200);assert.equal(r.tick,4);assert.ok(r.stateFor('a').position.x>3);assert.equal(r.gameStateFor('a').result.code,'lit');});
test('diagnostic output is detached and excludes connection identifiers',()=>{const r=setup(),before=r.inspection(),copy=r.inspection();copy.players[0].state.position.x=100;copy.players[0].intent.dx=-1;copy.game.players[0].pending[0].value='wrong';assert.deepEqual(r.inspection(),before);assert.equal(JSON.stringify(before).includes('"connection"'),false);});
test('old candidate simulation contract is rejected',async()=>{const {encodeHello,decodeHello}=await import('../dist/realm-contract.js');const hello=JSON.parse(encodeHello());delete hello.contract.simulationRevision;assert.throws(()=>decodeHello(JSON.stringify(hello)));});
