import test from 'node:test';import assert from 'node:assert/strict';import {mkdtemp,rm} from 'node:fs/promises';import {tmpdir} from 'node:os';import {join} from 'node:path';import {PGlite} from '@electric-sql/pglite';import {PGliteVisualSurface,QUALITY_PRESETS} from '../dist/visual-surface.js';import {createLocalRealmServer} from '../tools/realm-server.mjs';
test('real PGlite persists only validated visual quality across database reopen',async()=>{
 const path=await mkdtemp(join(tmpdir(),'wayfarer-visuals-'));let surface;
 try{let db=await PGlite.create(path);surface=new PGliteVisualSurface(db);assert.equal(await surface.getQuality(),undefined);await surface.setQuality('maximum');await assert.rejects(()=>surface.setQuality('forged_inventory'),/Invalid/);assert.equal(await surface.getQuality(),'maximum');const tables=await db.query("SELECT tablename FROM pg_tables WHERE schemaname='public'");assert.deepEqual(tables.rows.map(r=>r.tablename),['wayfarer_visual_preferences']);await surface.close();await assert.rejects(()=>surface.getQuality(),/closed/);db=await PGlite.create(path);surface=new PGliteVisualSurface(db);assert.equal(await surface.getQuality(),'maximum');await surface.setQuality('balanced');assert.equal(await surface.getQuality(),'balanced');await surface.clear();assert.equal(await surface.getQuality(),undefined);await surface.close();await surface.close();}
 finally{await surface?.close();await rm(path,{recursive:true,force:true});}
});
test('same-origin worker and WASM assets are served with narrow compilation policy',async()=>{
 const host=await createLocalRealmServer({autoTick:false});
 try{const wasm=await fetch(host.origin+'/preview/initdb.wasm');assert.equal(wasm.status,200);assert.equal(wasm.headers.get('content-type'),'application/wasm');assert.match(wasm.headers.get('content-security-policy'),/worker-src 'self'/);assert.match(wasm.headers.get('content-security-policy'),/'wasm-unsafe-eval'/);assert.equal(wasm.headers.get('cache-control'),'no-store');assert.ok(await WebAssembly.compile(await wasm.arrayBuffer()));for(const name of ['pglite-worker.bundle.js','pglite-plugin.bundle.js','pglite.data']){const response=await fetch(host.origin+'/preview/'+name);assert.equal(response.status,200);await response.arrayBuffer();}assert.equal(QUALITY_PRESETS.maximum.fps,60);assert.equal(QUALITY_PRESETS.balanced.bloom,false);}
 finally{await host.close();}
});
