import test from 'node:test';import assert from 'node:assert/strict';import {spawn} from 'node:child_process';import net from 'node:net';import http from 'node:http';import WS from 'ws';import {REALM_SUBPROTOCOL,encodeHello} from '../dist/realm-contract.js';
test('development bridge keeps hello/action frames as text and rejects foreign Host',async()=>{
 const reservation=net.createServer();await new Promise(r=>reservation.listen(0,'127.0.0.1',r));const port=reservation.address().port;await new Promise(r=>reservation.close(r));
 const child=spawn(process.execPath,['tools/visual-preview.mjs','--port',String(port)],{stdio:['ignore','pipe','pipe']});let ws;
 try{await new Promise((resolve,reject)=>{const timer=setTimeout(()=>reject(Error('Preview startup timeout')),5000);child.once('exit',()=>{clearTimeout(timer);reject(Error('Preview exited'));});child.stdout.on('data',chunk=>{if(String(chunk).includes('Development preview bridge')){clearTimeout(timer);resolve();}});});
  const origin=`http://127.0.0.1:${port}`;const status=await new Promise((resolve,reject)=>{http.get(origin,{headers:{Host:'foreign.invalid'}},res=>{res.resume();resolve(res.statusCode);}).on('error',reject);});assert.equal(status,403);ws=new WS(origin.replace('http:','ws:')+'/socket',REALM_SUBPROTOCOL,{headers:{Origin:origin}});const messages=[];ws.on('message',m=>messages.push(JSON.parse(m)));await new Promise((r,j)=>{ws.once('open',r);ws.once('error',j);});ws.send(encodeHello());
  const until=async predicate=>{for(let i=0;i<100;i++){if(predicate())return;await new Promise(r=>setTimeout(r,10));}throw Error('Bridge response timeout');};await until(()=>messages.some(m=>m.kind==='game'));assert.ok(messages.some(m=>m.kind==='welcome'));ws.send(JSON.stringify({kind:'action',sequence:0,action:'appearance',value:'seraphine'}));await until(()=>messages.some(m=>m.kind==='game'&&m.players.some(p=>p.skin==='seraphine')));
 }finally{ws?.terminate();child.kill('SIGTERM');await new Promise(r=>{if(child.exitCode!==null)r();else child.once('exit',r);});}
});
