import test from 'node:test';import assert from 'node:assert/strict';import {NullEngine,Scene} from '@babylonjs/core';import {WILDLIFE,WILDLIFE_SPECIES,wildlifeForChunk,wildlifeForRealm,wildlifeHabitat,wildlifePose} from '../dist/wildlife.js';import {Wildlife3D} from '../dist/wildlife-3d.js';import {BIOME_IDS} from '../dist/catalog.js';import {buildAtlas} from '../dist/world-atlas.js';import {REALM_WORLD,createRealmScene} from '../dist/realm-scene.js';import {CHUNK_SIZE} from '../dist/world.js';import {terrainSampler} from '../dist/navigation.js';
test('all ten biomes have reproducible, budgeted non-attackable wildlife sites',()=>{
 const ground=terrainSampler(REALM_WORLD);assert.equal(WILDLIFE_SPECIES.length,14);for(const biome of BIOME_IDS)assert.ok(wildlifeHabitat(biome).length>0);
 for(const a of buildAtlas(REALM_WORLD)){const cx=Math.floor(a.x/CHUNK_SIZE),cz=Math.floor(a.z/CHUNK_SIZE),npcs=wildlifeForChunk(REALM_WORLD,cx,cz);assert.deepEqual(npcs,wildlifeForChunk(REALM_WORLD,cx,cz));assert.ok(npcs.length<=6);for(const n of npcs){assert.ok(wildlifeHabitat(a.story.biome).includes(n.species));assert.equal(n.attackable,false);assert.equal(n.collidable,false);assert.equal(n.drops,false);assert.ok(n.position.x>=cx*64&&n.position.x<(cx+1)*64);assert.ok(ground(n.position.x,n.position.z).waterDepth<=.15);}}
 assert.throws(()=>wildlifeForChunk(REALM_WORLD,0,0,49));assert.throws(()=>wildlifeForChunk(REALM_WORLD,Infinity,0));assert.throws(()=>WILDLIFE.rabbit.habitats.push('desert'));
});
test('playable realm has a finite wildlife pocket and bounded paused roaming',()=>{
 const realm=createRealmScene(),ground=(x,z)=>realm.construction.terrainAt(x,z),npcs=wildlifeForRealm(REALM_WORLD,[realm.plan.start,realm.plan.goal],ground);assert.ok(npcs.length>=8);assert.equal(new Set(npcs.map(n=>n.id)).size,npcs.length);
 for(const n of npcs){for(let t=0;t<=100000;t+=500){const p=wildlifePose(n,t);assert.ok(Math.abs(p.x-n.position.x)<=.8);assert.ok(Math.abs(p.z-n.position.z)<=.65);assert.ok([p.x,p.z,p.hop,p.yaw].every(Number.isFinite));}assert.deepEqual(wildlifePose(n,0,true),wildlifePose(n,100000,true));}assert.throws(()=>wildlifePose(npcs[0],NaN));
});
test('all wildlife rigs are non-pickable, stable under updates, streamed out and fully disposed',()=>{
 const engine=new NullEngine(),scene=new Scene(engine),ground=()=>({height:2,waterDepth:0,slopeDegrees:0}),layer=new Wildlife3D(scene,ground),npcs=WILDLIFE_SPECIES.map((species,i)=>({id:'animal:'+species,species,position:{x:i*2,y:2,z:5},phase:i,attackable:false,collidable:false,drops:false}));
 try{layer.sync(npcs);assert.equal(layer.count,14);assert.ok(scene.meshes.length>100);assert.ok(scene.meshes.every(m=>m.isPickable===false&&m.checkCollisions===false));const count=scene.meshes.length;for(let t=0;t<100000;t+=250){layer.update(t,false);assert.equal(scene.meshes.length,count);assert.ok(scene.meshes.every(m=>m.position.asArray().every(Number.isFinite)));}assert.throws(()=>layer.sync([{...npcs[0],attackable:true}]));assert.equal(layer.count,14);layer.sync(npcs.slice(0,2));assert.equal(layer.count,2);layer.update(100000,true);const a=scene.meshes.map(m=>m.position.asArray());layer.update(150000,true);assert.deepEqual(scene.meshes.map(m=>m.position.asArray()),a);layer.sync([]);assert.equal(scene.meshes.length,0);layer.dispose();layer.dispose();assert.equal(scene.materials.length,0);assert.equal(scene.transformNodes.length,0);}finally{layer.dispose();scene.dispose();engine.dispose();}
});
test('wildlife holds its last dry position when a roaming sample becomes water',()=>{
 const engine=new NullEngine(),scene=new Scene(engine);let wet=false;const layer=new Wildlife3D(scene,()=>({height:2,waterDepth:wet?3:0,slopeDegrees:0})),npc={id:'mouse-test',species:'mouse',position:{x:5,y:2,z:4},phase:2,attackable:false,collidable:false,drops:false};
 try{layer.sync([npc]);layer.update(1000,false);const root=scene.getTransformNodeByName(npc.id),position=root.position.asArray();wet=true;layer.update(2000,false);assert.deepEqual(root.position.asArray(),position);}finally{layer.dispose();scene.dispose();engine.dispose();}
});
test('enhanced species details are batched and blinking resets under pause',()=>{const e=new NullEngine(),s=new Scene(e),layer=new Wildlife3D(s,()=>({height:0,waterDepth:0,slopeDegrees:0}));try{layer.sync([{id:'detail-rabbit',species:'rabbit',position:{x:0,y:0,z:0},phase:0,attackable:false,collidable:false,drops:false}]);const features=s.meshes.flatMap(m=>m.metadata?.features??[m.name]);assert.ok(features.some(n=>n.includes('inner-ear')));assert.ok(features.some(n=>n.includes('haunch')));assert.ok(s.meshes.length<25);const eye=s.getMeshByName('detail-rabbit:eye1');layer.update(0,false);assert.ok(eye.scaling.y<.01);layer.update(5000,true);assert.equal(eye.scaling.y,.045);}finally{layer.dispose();s.dispose();e.dispose();}});
