import chromium from '@sparticuz/chromium';import {chromium as pw} from 'playwright';import assert from 'node:assert/strict';import {mkdtemp,rm,writeFile} from 'node:fs/promises';import os from 'node:os';import path from 'node:path';
import {createLocalRealmServer} from '../tools/realm-server.mjs';import {LocalProfileStore} from '../tools/profile-store.mjs';import {createRealmScene} from '../dist/realm-scene.js';import {GameActions} from '../dist/game-actions.js';import {replayJournal} from '../tools/replay-journal.mjs';
const dir=await mkdtemp(path.join(os.tmpdir(),'wf-browser-')),profilePath=path.join(dir,'profiles.json'),scene=createRealmScene();
// Earn a fixture through the authoritative reducer; browser tests restore and manipulate it.
const g=new GameActions(scene.plan.start);g.join('fixture','p1');let seq=0;const act=(action,value)=>{g.receive('fixture',JSON.stringify({kind:'action',sequence:seq++,action,value}));g.commit(()=>scene.plan.start);};act('quest','accept');for(let i=0;i<3;i++){for(let j=0;j<20;j++)g.commit(()=>scene.plan.start);act('quest','gather');}act('quest','submit');act('claim','granite_maul');act('equip','granite_maul');
const store=await LocalProfileStore.open(profilePath),identity=await store.ensureSession();await store.save(identity.accountId,{version:1,position:{x:scene.plan.start.x,z:scene.plan.start.z},gameplay:g.persistentState('fixture')});
let host=await createLocalRealmServer({profilePath,recordReplay:true});const browser=await pw.launch({executablePath:new URL('./runtime/chromium',import.meta.url).pathname,args:chromium.args.filter(a=>a!=='--single-process'),env:{...process.env,LD_LIBRARY_PATH:new URL('./runtime/',import.meta.url).pathname},headless:true});const checks=[],errors=[];
try{const context=await browser.newContext({viewport:{width:1280,height:800}});context.setDefaultTimeout(60000);const cookie=identity.setCookie.split(';')[0].split('=');await context.addCookies([{name:cookie[0],value:cookie[1],url:host.origin,httpOnly:true,sameSite:'Strict'}]);await context.addInitScript(()=>{const Base=WebSocket;window.WebSocket=class extends Base{constructor(...args){super(...args);this.addEventListener('message',e=>{const m=JSON.parse(e.data);if(m.kind==='game')window.game=m;if(m.version===1)window.snap=m;});}};});const page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));await page.goto(host.origin);await page.locator('#join').click();await page.waitForFunction(()=>window.game?.inventory?.weapon==='granite_maul');checks.push('Restored server-owned earned fixture into Chromium');
 const duplicate=await context.newPage();await duplicate.goto(host.origin);await duplicate.locator('#join').click();await duplicate.waitForFunction(()=>!document.querySelector('#join').disabled);assert.equal(await duplicate.evaluate(()=>document.querySelector('#connection').textContent.startsWith('Connected')),false);checks.push('Same-cookie second browser tab denied');await duplicate.close();
 await page.bringToFront();await page.locator('#inventory-panel summary').click();await page.locator('#item-unequip').click();await page.waitForFunction(()=>window.game.inventory.weapon===null&&window.game.inventory.slots.includes('granite_maul'));await page.locator('#item-choice').selectOption('granite_maul');await page.locator('#item-equip').click();await page.waitForFunction(()=>window.game.inventory.weapon==='granite_maul');await page.locator('#appearance').selectOption('elder');await page.waitForFunction(()=>window.game.players.some(p=>p.skin==='elder'));checks.push('Equip/stow conserved item and appearance changed via browser controls');
 const port=Number(new URL(host.origin).port);await host.close();const first=host.exportReplay();replayJournal(JSON.stringify(first),scene.navigation);await writeFile(new URL('./rc6-before-restart.json',import.meta.url),JSON.stringify(first));host=await createLocalRealmServer({profilePath,port,recordReplay:true});await page.reload();await page.locator('#join').click();await page.waitForFunction(()=>window.game?.inventory?.weapon==='granite_maul'&&window.game.players.some(p=>p.skin==='elder'));assert.equal(await page.evaluate(()=>window.game.quest.tithes),0);checks.push('Host shutdown and reopen retained reward, equipment and appearance with same cookie');
 await page.locator('#leave').click();await page.waitForFunction(()=>!document.querySelector('#join').disabled);await page.waitForTimeout(300);await page.locator('#join').click();await page.waitForFunction(()=>window.game?.inventory?.weapon==='granite_maul'&&document.querySelector('#connection').textContent.startsWith('Connected'));checks.push('Explicit disconnect and rejoin retained inventory');
 await page.locator('#inventory-panel summary').click();await page.screenshot({path:new URL('./rc6-desktop.png',import.meta.url).pathname});await page.setViewportSize({width:390,height:844});await page.screenshot({path:new URL('./rc6-mobile.png',import.meta.url).pathname});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);checks.push('Mobile viewport has no horizontal overflow');
 await host.close();const journal=host.exportReplay(),replayed=replayJournal(JSON.stringify(journal),scene.navigation);await writeFile(new URL('./rc6-after-restart.json',import.meta.url),JSON.stringify(journal));assert.deepEqual(errors,[]);await writeFile(new URL('./rc6-browser-results.json',import.meta.url),JSON.stringify({browser:await browser.version(),checks,errors,replay:replayed,limits:['Earned fixture prepared through reducer before browser launch','Loopback local profiles, not production auth','Chromium only; no physical mobile device','No power-loss or multi-process durability test']},null,2));console.log(JSON.stringify({checks,errors,replayed}));
}finally{await browser.close();await host.close().catch(()=>{});await rm(dir,{recursive:true,force:true});}
