export const HUD_TABS=['practice','combat','gathering','quest','inventory','settings'] as const;
export type HudTab=typeof HUD_TABS[number];
export const isHudTab=(x:unknown):x is HudTab=>typeof x==='string'&&(HUD_TABS as readonly string[]).includes(x);
export function initRealmHud(doc:Document=document){let compact=false,tab:HudTab='practice',size='normal',height=55,visual=true,living=true;try{const raw=globalThis.localStorage?.getItem('wayfarer.hud.v1')??'null';const saved=raw.length<=1024?JSON.parse(raw):null;if(saved&&isHudTab(saved.tab)&&typeof saved.compact==='boolean'){tab=saved.tab;compact=saved.compact;if(['small','normal','large'].includes(saved.size))size=saved.size;if(Number.isInteger(saved.height)&&saved.height>=35&&saved.height<=80)height=saved.height;if(typeof saved.visual==='boolean')visual=saved.visual;if(typeof saved.living==='boolean')living=saved.living;}}catch{}
 const save=()=>{try{globalThis.localStorage?.setItem('wayfarer.hud.v1',JSON.stringify({tab,compact,size,height,visual,living}));}catch{}};
 const apply=()=>{const body=doc.body;body?.setAttribute?.('data-hud-size',size);body?.style?.setProperty('--hud-height',height+'dvh');const v=doc.querySelector<HTMLElement>('#visual-surface'),l=doc.querySelector<HTMLElement>('#living-realm');if(v)v.hidden=!visual;if(l)l.hidden=!living;const sz=doc.querySelector<HTMLSelectElement>('#hud-size'),ht=doc.querySelector<HTMLInputElement>('#hud-height'),vc=doc.querySelector<HTMLInputElement>('#show-visual'),lc=doc.querySelector<HTMLInputElement>('#show-living');if(sz)sz.value=size;if(ht)ht.value=String(height);const label=doc.querySelector<HTMLElement>('#hud-height-value');if(label)label.textContent=height+'%';if(vc)vc.checked=visual;if(lc)lc.checked=living;doc.querySelector('footer')?.classList?.toggle('hud-collapsed',compact);const toggle=doc.querySelector<HTMLButtonElement>('#hud-toggle');if(toggle){toggle.textContent=compact?'▣ Open game panels':'▣ Minimise game panels';toggle.setAttribute?.('aria-expanded',String(!compact));}for(const p of doc.querySelectorAll<HTMLElement>('[data-hud-panel]'))p.hidden=p.dataset.hudPanel!==tab;for(const b of doc.querySelectorAll<HTMLElement>('[data-hud-tab]')){const active=b.dataset.hudTab===tab;b.setAttribute?.('aria-selected',String(active));b.setAttribute?.('tabindex',active?'0':'-1');}};
 const choose=(value:unknown)=>{if(isHudTab(value)){tab=value;compact=false;apply();save();}};
 for(const b of doc.querySelectorAll<HTMLButtonElement>('[data-hud-tab]')){b.addEventListener('click',()=>choose(b.dataset.hudTab));b.addEventListener('keydown',event=>{if(!['ArrowLeft','ArrowRight','Home','End'].includes(event.key))return;event.preventDefault();const index=HUD_TABS.indexOf(tab),next=event.key==='Home'?0:event.key==='End'?HUD_TABS.length-1:(index+(event.key==='ArrowRight'?1:-1)+HUD_TABS.length)%HUD_TABS.length;choose(HUD_TABS[next]);doc.querySelector<HTMLButtonElement>(`[data-hud-tab="${tab}"]`)?.focus?.();});}
 doc.querySelector('#hud-reset')?.addEventListener('click',()=>{compact=false;tab='settings';size='normal';height=55;visual=true;living=true;apply();save();});
 doc.querySelector('#hud-close')?.addEventListener('click',()=>{compact=true;apply();save();doc.querySelector<HTMLButtonElement>('#hud-toggle')?.focus?.();});
 doc.querySelector('#hud-size')?.addEventListener('change',()=>{const value=doc.querySelector<HTMLSelectElement>('#hud-size')?.value;if(['small','normal','large'].includes(value??'')){size=value!;apply();save();}});
 doc.querySelector('#hud-height')?.addEventListener('input',()=>{const value=Number(doc.querySelector<HTMLInputElement>('#hud-height')?.value);if(Number.isInteger(value)&&value>=35&&value<=80){height=value;apply();save();}});
 for(const key of ['visual','living'] as const){doc.querySelector('#show-'+key)?.addEventListener('change',()=>{const enabled=!!doc.querySelector<HTMLInputElement>('#show-'+key)?.checked;if(key==='visual')visual=enabled;else living=enabled;apply();save();});doc.querySelector('#close-'+key)?.addEventListener('click',()=>{if(key==='visual')visual=false;else living=false;apply();save();doc.querySelector<HTMLButtonElement>('#hud-toggle')?.focus?.();});}
 doc.addEventListener?.('keydown',event=>{if(event.key==='Escape'&&!['INPUT','SELECT','TEXTAREA'].includes((event.target as HTMLElement)?.tagName)){compact=true;apply();save();}});
 doc.querySelector('#hud-toggle')?.addEventListener('click',()=>{compact=!compact;apply();save();});apply();return {choose,get state(){return {tab,compact,size,height,visual,living};}};
}
