import {isPracticeSkill,checkedPracticeTick} from './practice.js';import type {SkillId} from './skill-directory.js';
export interface PracticeChallenge {token:string;skill:SkillId;reward:'practice'|'gathering';step:number;target:number;readyTick:number;expiresTick:number}
export const PRACTICE_STEPS=3,PRACTICE_ATTEMPT_TICKS=300;
export const PRACTICE_VERBS:Record<SkillId,readonly [string,string,string]>={attack:['Aim','Align','Strike'],strength:['Brace','Push','Release'],defence:['Set feet','Raise shield','Block'],ranged:['Aim','Draw','Release'],magic:['Focus','Trace','Channel'],hitpoints:['Breathe','Brace','Stretch'],prayer:['Breathe','Reflect','Centre'],woodcutting:['Align axe','Brace','Chop'],mining:['Find seam','Aim pick','Tap'],fishing:['Aim cast','Cast','Reel'],agility:['Set foot','Balance','Step'],cooking:['Measure','Stir','Serve'],crafting:['Shape','Smooth','Finish'],firemaking:['Gather tinder','Arrange','Prepare spark'],fletching:['Align shaft','Fit feather','Bind'],herblore:['Identify','Sort','Measure'],runecrafting:['Focus','Trace','Seal'],slayer:['Observe','Track','Identify'],smithing:['Align billet','Tap','Shape'],thieving:['Observe latch','Feel seam','Open'],farming:['Loosen soil','Tend','Water'],construction:['Align joint','Fit','Secure'],hunter:['Read tracks','Place frame','Check release']};
// Replay-friendly variation is not secret entropy or proof of human input.
function mix(text:string){let n=2166136261;for(const c of text)n=Math.imul(n^c.charCodeAt(0),16777619);return n>>>0;}
export function beginPractice(skill:SkillId,id:string,tick:number,sequence:number,reward:'practice'|'gathering'='practice'):PracticeChallenge {const token=`${id}-${tick}-${sequence}`,n=mix(`${id}:${skill}:${token}`);return checkedPracticeChallenge({token,skill,reward,step:0,target:n%4,readyTick:tick+8+n%13,expiresTick:tick+PRACTICE_ATTEMPT_TICKS},tick);}
export function advancePractice(c:PracticeChallenge,tick:number):PracticeChallenge {const n=mix(`${c.token}:${c.skill}:${c.step+1}`);return checkedPracticeChallenge({...c,step:c.step+1,target:(c.target+1+n%3)%4,readyTick:tick+8+n%13},tick);}
export function checkedPracticeChallenge(x:unknown,tick:number):PracticeChallenge {if(!x||typeof x!=='object'||Array.isArray(x))throw Error('Invalid practice challenge');const r=x as Record<string,unknown>,keys=['token','skill','reward','step','target','readyTick','expiresTick'];if(Object.keys(r).length!==keys.length||!keys.every(k=>Object.hasOwn(r,k))||typeof r.token!=='string'||!/^p[1-9][0-9]{0,15}-\d{1,16}-\d{1,16}$/.test(r.token)||!isPracticeSkill(r.skill)||!['practice','gathering'].includes(r.reward as string)||r.reward==='gathering'&&!['woodcutting','mining','fishing'].includes(r.skill as string)||!Number.isInteger(r.step)||Number(r.step)<0||Number(r.step)>=PRACTICE_STEPS||!Number.isInteger(r.target)||Number(r.target)<0||Number(r.target)>3)throw Error('Invalid practice challenge');const ready=checkedPracticeTick(r.readyTick,tick+20),expires=checkedPracticeTick(r.expiresTick,tick+PRACTICE_ATTEMPT_TICKS);if(expires<=tick||ready>=expires)throw Error('Invalid practice deadline');return {...r} as unknown as PracticeChallenge;}
export function isPracticeResponse(x:unknown):x is string {return typeof x==='string'&&(x==='cancel'||/^p[1-9][0-9]{0,15}-\d{1,16}-\d{1,16}\/[0-2]\/[0-3]$/.test(x));}
export function practiceResponse(c:PracticeChallenge,target:number){if(!Number.isInteger(target)||target<0||target>3)throw Error('Invalid practice target');return `${c.token}/${c.step}/${target}`;}
