import test from 'node:test';import assert from 'node:assert/strict';
import {ITEMS,checkedInventory,freshInventory,isItem} from '../dist/inventory.js';
import {GameActions,decodeGameState} from '../dist/game-actions.js';
import {RealmRuntime} from '../dist/realm-runtime.js';
import {NavigationWorld} from '../dist/navigation.js';
const pos={x:0,y:0,z:0};
function setup(){const g=new GameActions(pos);g.join('a','p1');let seq=0;return {g,act:(action,value)=>{g.receive('a',JSON.stringify({kind:'action',sequence:seq++,action,value}));g.commit(()=>pos);return g.snapshot('a',['p1']);}};}
test('inventory rejects sparse slots and item catalog cannot be changed',()=>{assert.throws(()=>checkedInventory({...freshInventory(),slots:Array(20)}));assert.throws(()=>{ITEMS.admin_sword={name:'Injected'};});assert.throws(()=>{ITEMS.reed_blade.name='Injected';});assert.equal(isItem('admin_sword'),false);});
test('resource and gather clocks reject impossible snapshots',()=>{const {g}=setup();const s=g.snapshot('a',['p1']);for(const patch of [{stock:0,respawnTick:0},{stock:0,respawnTick:201},{stock:1,respawnTick:1}])assert.throws(()=>decodeGameState(JSON.stringify({...s,patch})));assert.throws(()=>decodeGameState(JSON.stringify({...s,quest:{...s.quest,gatherReadyTick:1}})));assert.throws(()=>decodeGameState(JSON.stringify({...s,quest:{...s.quest,status:'active',gatherReadyTick:21}})));assert.doesNotThrow(()=>decodeGameState(JSON.stringify({...s,patch:{stock:0,respawnTick:200}})));});
test('duplicate player identity and malformed connections cannot enter gameplay',()=>{const {g}=setup(),before=g.inspection();for(const c of ['',null,'x'.repeat(129)])assert.throws(()=>g.join(c,'p2'));assert.throws(()=>g.join('b','p1'));assert.deepEqual(g.inspection(),before);});
test('final candidate failure discards reward payment, item grant, result and tick',()=>{const {g,act}=setup();act('quest','accept');for(let i=0;i<3;i++){for(let j=0;j<20;j++)g.commit(()=>pos);act('quest','gather');}act('quest','submit');g.receive('a',JSON.stringify({kind:'action',sequence:100,action:'claim',value:'granite_maul'}));const before=g.inspection(),validate=GameActions.prototype.validate;try{GameActions.prototype.validate=function(ids){validate.call(this,ids);if(this.inspection().players[0].inventory.rewardClaimed)throw Error('Injected final validation failure');};assert.throws(()=>g.commit(()=>pos),/Injected/);assert.deepEqual(g.inspection(),before);}finally{GameActions.prototype.validate=validate;}g.commit(()=>pos);assert.equal(g.snapshot('a',[]).inventory.weapon,null);assert.equal(g.snapshot('a',[]).inventory.slots[0],'granite_maul');});
test('realm discards clock divergence before publishing movement',()=>{const nav=new NavigationWorld(()=>({height:0,slopeDegrees:0,waterDepth:0}),{bounds:{minX:-20,maxX:20,minZ:-20,maxZ:20}});const r=new RealmRuntime(nav,{beacon:pos});r.join('a',pos);r.receive('a',JSON.stringify({sequence:0,dx:1,dz:0}));const before=r.inspection(),staged=GameActions.prototype.stagedCommit;try{GameActions.prototype.stagedCommit=function(fn){const next=staged.call(this,fn);next.tick++;return next;};assert.throws(()=>r.advance(50),/clock mismatch/);assert.equal(r.status,'faulted');const after=r.inspection();assert.equal(after.tick,before.tick);assert.deepEqual(after.players,before.players);assert.deepEqual(after.game,before.game);}finally{GameActions.prototype.stagedCommit=staged;}});
test('5000 seeded mixed actions preserve inventory and resource invariants',()=>{const {g}=setup();let seed=92871;const choices=[['quest','accept'],['quest','gather'],['quest','submit'],['claim','reed_blade'],['claim','granite_maul'],['equip','reed_blade'],['unequip','weapon'],['beacon','light'],['appearance','elder']];for(let i=0;i<5000;i++){seed=(Math.imul(seed,1664525)+1013904223)>>>0;const [action,value]=choices[seed%choices.length];const packet=JSON.stringify({kind:'action',sequence:i,action,value});assert.ok(g.receive('a',packet));assert.equal(g.receive('a',packet),false);g.commit(()=>seed%7===0?{x:10,y:0,z:0}:pos);const s=decodeGameState(JSON.stringify(g.snapshot('a',['p1'])));const count=s.inventory.slots.filter(Boolean).length+Number(s.inventory.weapon!==null);assert.equal(count,Number(s.inventory.rewardClaimed));assert.ok(s.quest.tithes+count<=1);assert.ok(s.patch.stock>=0&&s.patch.stock<=3);}});
