import test from 'node:test';import assert from 'node:assert/strict';
import {GameActions,decodeAction,decodeGameState} from '../dist/game-actions.js';
const pos={x:0,y:0,z:0},packet=(sequence,action='beacon',value='light')=>JSON.stringify({kind:'action',sequence,action,value});
const setup=()=>{const g=new GameActions(pos);g.join('a','p1');g.join('b','p2');return g;};
test('actions wait for tick, distance is authoritative and effects are idempotent',()=>{const g=setup();assert.ok(g.receive('a',packet(0)));assert.equal(g.snapshot('a',[]).beacon.lit,false);g.commit(()=>({x:4,y:0,z:0}));assert.equal(g.snapshot('a',[]).result.code,'out_of_range');assert.ok(g.receive('a',packet(1)));g.commit(()=>pos);assert.equal(g.snapshot('b',[]).beacon.lit,true);assert.equal(g.receive('a',packet(1)),false);assert.ok(g.receive('b',packet(0)));g.commit(()=>pos);assert.equal(g.snapshot('b',[]).result.code,'already_lit');});
test('identity fields, unknown skins and malformed commands fail closed',()=>{const g=setup();for(const p of ['null','{}',packet(-1),packet(0,'appearance','admin'),packet(0).replace('"light"','"light","id":"p2"')]){assert.throws(()=>decodeAction(p));assert.equal(g.receive('a',p),false);}assert.equal(g.receive('missing',packet(0)),false);});
test('cosmetics replicate only for visible identities and queued actions are bounded',()=>{const g=setup();for(let i=0;i<8;i++)assert.ok(g.receive('a',packet(i,'appearance','elder')));assert.equal(g.receive('a',packet(8)),false);g.commit(()=>pos);assert.deepEqual(g.snapshot('b',['p1']).players,[{id:'p1',skin:'elder',weapon:null}]);assert.deepEqual(decodeGameState(JSON.stringify(g.snapshot('a',['p1','p2']))),g.snapshot('a',['p1','p2']));g.leave('a');assert.deepEqual(g.snapshot('b',['p1']).players,[]);});
test('failed action calculation preserves all game results and effects',()=>{const g=setup();g.receive('a',packet(0));g.receive('b',packet(0));const before=g.snapshot('a',['p1','p2']);assert.throws(()=>g.commit(c=>{if(c==='b')throw new Error('fault');return pos;}));assert.deepEqual(g.snapshot('a',['p1','p2']),before);});
test('invalid server game messages are rejected',()=>{const valid=setup().snapshot('a',['p1']);for(const patch of [{extra:1},{revision:-1},{players:[{id:'p1',skin:'invalid'}]},{beacon:{position:{x:null,y:0,z:0},lit:false}},{result:{sequence:0,code:'grant_gold'}}])assert.throws(()=>decodeGameState(JSON.stringify({...valid,...patch})));});
