import test from 'node:test';import assert from 'node:assert/strict';
import {GameActions,decodeAction,decodeGameState} from '../dist/game-actions.js';
import {freshInventory,checkedInventory,grantReward,equipItem,unequipItem} from '../dist/inventory.js';
const pos={x:0,y:0,z:0};
function setup(){const g=new GameActions(pos);g.join('a','p1');g.join('b','p2');let sequence=0;const packet=(action,value)=>JSON.stringify({kind:'action',sequence:sequence++,action,value});const act=(action,value,position=pos)=>{assert.ok(g.receive('a',packet(action,value)));g.commit(()=>position);return g.snapshot('a',['p1','p2']);};const finish=()=>{act('quest','accept');for(let i=0;i<3;i++){for(let j=0;j<20;j++)g.commit(()=>pos);act('quest','gather');}act('quest','submit');};return {g,packet,act,finish};}
test('one reward consumes one token; repeated claims cannot duplicate items',()=>{const {act,finish}=setup();assert.equal(act('claim','granite_maul').result.code,'reward_unavailable');finish();assert.equal(act('claim','granite_maul',{x:4,y:0,z:0}).result.code,'out_of_range');const s=act('claim','granite_maul');assert.equal(s.quest.tithes,0);assert.equal(s.inventory.slots.filter(Boolean).length,1);assert.equal(act('claim','ash_staff').result.code,'reward_unavailable');assert.equal(act('quest','submit').quest.tithes,0);assert.doesNotThrow(()=>decodeGameState(JSON.stringify(s)));});
test('equip and stow conserve item ownership and share only equipment',()=>{const {g,act,finish}=setup();finish();act('claim','reed_blade');assert.equal(act('equip','ash_staff').result.code,'item_unavailable');const s=act('equip','reed_blade');assert.equal(s.inventory.weapon,'reed_blade');assert.equal(s.inventory.slots.filter(Boolean).length,0);const remote=g.snapshot('b',['p1']);assert.equal(remote.players[0].weapon,'reed_blade');assert.equal(remote.inventory.rewardClaimed,false);assert.ok(!('inventory' in remote.players[0]));assert.equal(act('equip','reed_blade').result.code,'item_unavailable');assert.equal(act('unequip','weapon').inventory.slots[0],'reed_blade');assert.equal(act('unequip','weapon').result.code,'item_unavailable');});
test('duplicate queued reward claims and replayed packet sequences grant only once',()=>{const {g,packet,finish}=setup();finish();const p=packet('claim','ash_staff');assert.ok(g.receive('a',p));assert.equal(g.receive('a',p),false);g.receive('a',packet('claim','granite_maul'));g.commit(()=>pos);assert.deepEqual(g.snapshot('a',[]).inventory.slots.filter(Boolean),['ash_staff']);});
test('candidate failure rolls back both payment and item grant',()=>{const {g,packet,finish}=setup();finish();g.receive('a',packet('claim','ash_staff'));g.receive('b',JSON.stringify({kind:'action',sequence:0,action:'beacon',value:'light'}));const before=g.inspection();assert.throws(()=>g.stagedCommit(c=>{if(c==='b')throw Error('fault');return pos;}));assert.deepEqual(g.inspection(),before);});
test('strict item codecs reject unknown IDs, client grants and inconsistent snapshots',()=>{const {g}=setup();for(const p of [{kind:'action',sequence:1,action:'claim',value:'admin_sword'},{kind:'action',sequence:1,action:'equip',value:'reed_blade',count:100}])assert.throws(()=>decodeAction(JSON.stringify(p)));const s=g.snapshot('a',[]);assert.throws(()=>decodeGameState(JSON.stringify({...s,inventory:{...s.inventory,weapon:'reed_blade'}})));assert.throws(()=>checkedInventory({slots:Array(21).fill(null),weapon:null,rewardClaimed:false}));});
test('inventory transitions and snapshots do not alias source arrays',()=>{const a=freshInventory(),b=grantReward(a,'ash_staff'),c=equipItem(b,'ash_staff'),d=unequipItem(c);assert.equal(a.rewardClaimed,false);assert.equal(b.slots[0],'ash_staff');assert.equal(c.slots[0],null);d.slots[0]=null;assert.equal(c.weapon,'ash_staff');const {g,finish,act}=setup();finish();const s=act('claim','reed_blade');s.inventory.slots[0]=null;assert.equal(g.snapshot('a',[]).inventory.slots[0],'reed_blade');});
