import test from 'node:test';
import assert from 'node:assert/strict';
import {GameActions,decodeAction,decodeGameState} from '../dist/game-actions.js';
const camp={x:0,y:0,z:0},patch={x:20,y:0,z:0};
function setup(){const g=new GameActions(patch,camp);g.join('a','p1');g.join('b','p2');let n=0;return {g,act:(who,value,pos)=>{assert.ok(g.receive(who,JSON.stringify({kind:'action',sequence:n++,action:'quest',value})));g.commit(()=>pos);return g.snapshot(who,[]);},wait:n=>{for(let i=0;i<n;i++)g.commit(()=>patch);}};}
test('quest requires proximity, acceptance and complete inventory; reward cannot repeat',()=>{const {g,act,wait}=setup();assert.equal(act('a','accept',patch).result.code,'out_of_range');assert.equal(act('a','gather',patch).result.code,'quest_not_active');assert.equal(act('a','accept',camp).quest.status,'active');assert.equal(act('a','submit',camp).result.code,'requirements_not_met');for(let i=0;i<3;i++){wait(20);assert.equal(act('a','gather',patch).quest.reeds,i+1);}assert.equal(act('a','submit',patch).result.code,'out_of_range');assert.equal(act('a','submit',camp).quest.tithes,1);assert.equal(act('a','submit',camp).result.code,'quest_not_active');assert.equal(act('a','accept',camp).result.code,'quest_unavailable');assert.equal(g.snapshot('a',[]).quest.tithes,1);assert.equal(g.snapshot('b',[]).quest.status,'available');});
test('shared finite patch and tick cooldown prevent packet harvesting; stock regrows',()=>{const {g,act,wait}=setup();act('a','accept',camp);act('b','accept',camp);act('a','gather',patch);assert.equal(act('a','gather',patch).result.code,'gather_wait');act('b','gather',patch);wait(20);assert.equal(act('a','gather',patch).patch.stock,0);assert.equal(act('b','gather',patch).result.code,'patch_empty');wait(199);assert.equal(g.snapshot('b',[]).patch.stock,3);assert.equal(act('b','gather',patch).quest.reeds,2);});
test('client cannot supply inventory, rewards, quantity or a target position',()=>{for(const field of ['reeds','tithes','quantity','position'])assert.throws(()=>decodeAction(JSON.stringify({kind:'action',sequence:0,action:'quest',value:'gather',[field]:99})));const {g}=setup();const s=g.snapshot('a',[]);assert.throws(()=>decodeGameState(JSON.stringify({...s,quest:{...s.quest,tithes:1}})));});
test('failed candidate discards resource consumption and private quest transitions',()=>{const {g,act}=setup();act('a','accept',camp);act('b','accept',camp);for(const who of ['a','b'])g.receive(who,JSON.stringify({kind:'action',sequence:20,action:'quest',value:'gather'}));const before=g.inspection();assert.throws(()=>g.stagedCommit(who=>{if(who==='b')throw Error('fault');return patch;}));assert.deepEqual(g.inspection(),before);});
test('recipient inventory is detached and absent from other player records',()=>{const {g,act}=setup();act('a','accept',camp);act('a','gather',patch);const s=g.snapshot('a',['p1','p2']);s.quest.reeds=99;assert.equal(g.snapshot('a',[]).quest.reeds,1);assert.ok(g.snapshot('b',['p1']).players.every(p=>!('quest' in p)));assert.equal(g.snapshot('b',[]).quest.reeds,0);});
